channels:
  - https://{{ BODO_CONDA_USERNAME }}:{{ BODO_CONDA_TOKEN }}@bodo.jfrog.io/artifactory/api/conda/bodo.ai
  - conda-forge
  - pytorch
  - default
dependencies:
  - bodo
  - bokeh
  - boto3
  - botocore
  - cmake  # used by horovod
  - dask
  - ipyparallel
  - ipython
  - jupyterlab
  - numpy
  - matplotlib
  - pandas
  - pip
  - pytest
  - python
  - pytorch >=1.5
  - scipy
  - scikit-learn
  - torchvision >=0.6
  # development
  - pytest
  - pip:
    - nbmake==0.1.post1
    - horovod[pytorch]
