name: test
on:
  # as it will take the license from github secrect, it need to be
  # triggered just for push (or similar, not for pull request).
  push:
    branches:
    - '*'
jobs:
  test_suite:
    name: Pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - name: create .env and bodo license
        shell: bash -l {0}
        env:
          BODO_LICENSE_CONTENT: ${{ secrets.BODO_LICENSE_CONTENT }}
          BODO_CONDA_USERNAME: ${{ secrets.BODO_CONDA_USERNAME }}
          BODO_CONDA_TOKEN: ${{ secrets.BODO_CONDA_TOKEN }}
        run: |
          make create-ci-dotenv-file
          make create-bodo-license-file

      - name: create conda env file
        run: make create-conda-env-file

      - uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: bodoai-nb
           environment-file: _setup/environment-dev.yaml
           python-version: ${{ matrix.python-version }}
           auto-activate-base: false
           auto-update-conda: false
           channels: conda-forge

      - name: conda config
        shell: bash -l {0}
        run: conda config --show

      - name: conda list
        shell: bash -l {0}
        run: conda list

      - name: test notebooks
        shell: bash -l {0}
        run: |
          make run-tests
